version: "3"
services:
  moonshot-server:
    image: "${IMAGE_NAME}"
    command: bash -c /project/DockerScripts/run.sh
    ports:
      - "7777:7777/udp"
      - "7778:7778"
      - "80:80"
      - "8080:8080"
