version: "3"
services:
  test:
    image: httpd:2.4
    command: /bin/sh -c "echo '<html><body>Hello</body></html>' >  /usr/local/apache2/htdocs/index.html && httpd-foreground"
    ports:
      - "7777:7777/udp"
      - "7778:7778"
      - "80:80"
      - "8080:8080"
